### ISSUE TITLE
Revert GCC 11 Linux pinning

### ISSUE THREAD

**Issue by basnijholt** [conda-forge/qsimcirq-feedstock#10]
Once issue ( [pybind/pybind11#4606](https://github.com/pybind/pybind11/issues/4606) ) is resolved, would revert commit ( [8e991f4](https://github.com/conda-forge/qsimcirq-feedstock/pull/9/commits/8e991f45d9982c858ade95f10678f07e9bd84786) ) and re-render

Copied from @jakirkham from https://github.com/conda-forge/pp-sketchlib-feedstock/issues/43

**Comment by jakirkham** [comment]
Think we can do this now. In pybind11's 2.12.0 release, they included this fix: https://github.com/pybind/pybind11/commit/3414c56b6c7c521d868c9a137ca2ace2e26b5b2e

We included that release in conda-forge some time ago: https://github.com/conda-forge/pybind11-feedstock/pull/94

So would just drop this `use_local: true` line and [re-render]( https://conda-forge.org/docs/maintainer/updating_pkgs/#rerendering-feedstocks ):

https://github.com/conda-forge/qsimcirq-feedstock/blob/0da0717d36e8ddaf9498700a1b78633404ed9513/.ci_support/migrations/cuda120.yaml#L5-L8
